version: "3.4"

services:
  redis:
      image: redis:latest
      ports:
        -  6397:6397
      restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=postgresdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
    ports:
      - 5432:5432
    restart: unless-stopped
      
    volumes:
      - ./db/data/postgres:/var/lib/postgres/data
      - /home/app/server/node_modules

  server:
    build: ./server
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=postgresdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - NODE_ENV=prod
      - REDIS_HOST=redis
    ports:
      - 4000:4000
    volumes:
      - ./server:/home/app/server
      - /home/app/server/node_modules
    command: yarn start
    links:
      - postgres
      - redis
    depends_on:
      - redis
      - postgres


  web:
    build: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/home/app/web
      - /home/app/web/node_modules
    links:
      - server
    command:  /bin/sh -c "yarn build && yarn start"
    depends_on:
      - redis
      - postgres
      - server
