version: "3.4"

services:
  redis:
      image: redis:latest
      ports:
        -  6397:6397
      restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=postgresdb
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./db/data/postgres:/var/lib/postgres/data

  server:
    build: ./server
    environment:
      - NODE_ENV=prod
    ports:
      - 4000:4000
    volumes:
      - ./server:/home/app/server
    links:
      - postgres
      - redis
    command: yarn dev
    depends_on:
      - redis
      - postgres

  web:
    build: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/home/app/web
    links:
      - server
    command: yarn dev
    depends_on:
      - redis
      - postgres
      - server
